---

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php package
      ansible.builtin.package:
        update_cache: true
        name: 
          - "{{ apache_package }}" 
          - "{{ php_package }}"
        state: latest

