---

- hosts: web_servers
  become: true
  tasks:

    - name: remove apache package
      ansible.builtin.apt:
        update_cache: true
        name: 
          - apache2 
          - libapache2-mod-php
        state: absent
  