---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (Ubuntu)
      tags: allways
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: install updates (CentOS)
      tags: allways
      ansible.builtin.dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php package (Debian based)
      tags: apache,apache2,ubuntu
      ansible.builtin.apt:
        name: 
          - apache2 
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install apache and php package (RedHat based)
      tags: apache,httpd,centos
      ansible.builtin.dnf:
        name: 
          - httpd 
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: copy default html file for site
      tags: apache,apache2,httpd
      ansible.builtin.copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (Debian based)
      tags: db,mariadb,ubuntu
      ansible.builtin.apt:
        name: 
          - mariadb-server 
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install mariadb package (RedHat based)
      tags: db,mariadb,centos
      ansible.builtin.dnf:
        name: 
          - mariadb 
        state: latest
      when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      ansible.builtin.package:
        name: 
          - samba 
        state: latest

