---

- hosts: all
  become: true
  pre_tasks:
    - name: update repository cache (Ubuntu)
      tags: always
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: update repository cache (CentOS)
      tags: always
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: ansible_distribution in ["CentOS", "Rocky"]

- hosts: all
  become: true
  roles:
    - base

- hosts: workstationss
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
    