---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (Ubuntu)
      tags: allways
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install updates (CentOS)
      tags: allways
      ansible.builtin.dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution in ["CentOS", "Rocky"]

- hosts: workstations
  become: true

  tasks:
  - name: install unzip
    ansible.builtin.package:
      name: unzip

  - name: install terraform
    ansible.builtin.unarchive:
      src: https://releases.hashicorp.com/terraform/1.11.2/terraform_1.11.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: true
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php package (Debian based)
      tags: apache,apache2,ubuntu
      ansible.builtin.apt:
        name: 
          - apache2 
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install apache and php package (RedHat based)
      tags: apache,httpd,centos
      ansible.builtin.dnf:
        name: 
          - httpd 
          - php
        state: latest
      when: ansible_distribution in ["CentOS", "Rocky"]

    - name: copy default html file for site
      tags: apache,apache2,httpd
      ansible.builtin.copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (Debian based)
      tags: db,mariadb,ubuntu
      ansible.builtin.apt:
        name: 
          - mariadb-server 
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install mariadb package (RedHat based)
      tags: db,mariadb,centos
      ansible.builtin.dnf:
        name: 
          - mariadb 
        state: latest
      when: ansible_distribution in ["CentOS", "Rocky"]

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      ansible.builtin.package:
        name: 
          - samba 
        state: latest

