- name: install apache and php package (Debian based)
  tags: apache,apache2,ubuntu
  ansible.builtin.apt:
    name: 
      - apache2 
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: install apache and php package (RedHat based)
  tags: apache,httpd,centos
  ansible.builtin.dnf:
    name: 
      - httpd 
      - php
    state: latest
  when: ansible_distribution in ["CentOS", "Rocky"]

- name:  start httpd service (CentOS)
  tags: apache,centos,httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
  when: ansible_distribution in ["CentOS", "Rocky"]

- name: change e-mail address for admin
  tags: apache,centos,httpd
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution in ["CentOS","Rocky"]
  register: httpd

- name: restart httpd (CentOS)
  tags: apache,centos,httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: httpd.changed

- name:  open port 80 (CentOS)
  tags: apache,centos,httpd
  ansible.posix.firewalld:
    port: 80/tcp
    state: enabled
    permanent: true
    immediate: true
  when: ansible_distribution in ["CentOS", "Rocky"]

- name: copy default html file for site
  tags: apache,apache2,httpd
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

