- name: install apache and php package
  tags: apache,httpd,php
  ansible.builtin.package:
    name: 
      - "{{ apache_package_name }}" 
      - "{{ php_package_name }}"
    state: latest

- name:  start and enable httpd service
  tags: apache,httpd
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: true

- name: change e-mail address for admin
  tags: apache,centos,httpd
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution in ["CentOS","Rocky"]
  notify: restart_apache

- name:  open port 80 (CentOS)
  tags: apache,centos,httpd
  ansible.posix.firewalld:
    port: 80/tcp
    state: enabled
    permanent: true
    immediate: true
  when: ansible_distribution in ["CentOS", "Rocky"]

- name: copy default html file for site
  tags: apache,apache2,httpd
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

