- name: install unzip
  ansible.builtin.package:
    name: unzip

- name: install terraform
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/1.11.2/terraform_1.11.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
    mode: 0755
    owner: root
    group: root

